#!/usr/bin/env python3
"""Regenerate the `## Index` block at the top of the two case-law files (Fable B-2).

assumptions_audit.md (97 entries) and gemini_review_patterns.md are read wholesale to recall "have we seen
this failure class?" — a 700+-line read for a one-line answer. This inserts/refreshes a scannable index of
`#N — <lesson>` (the entry HEADERS already ARE the one-sentence lessons), so recall is a 60-line read + a
grep. Re-runnable and idempotent (it replaces the block between the AUTO markers) — so it's ALSO the
maintenance mechanism: add an entry, re-run `python3 tools/reindex_caselaw.py`, commit. Stdlib-only.
"""
import re
import sys

FILES = (
    "docs/failures/assumptions_audit.md",
    "docs/failures/gemini_review_patterns.md",
)
ENTRY_RE = re.compile(r"^(#{2,3})\s+(\d+)\.\s+(.+?)\s*$")   # "## N. …" or "### N. …" (each file uses one level)
START = "<!-- INDEX:START (auto-generated by tools/reindex_caselaw.py — do not hand-edit) -->"
END = "<!-- INDEX:END -->"

# --- Malformed-entry detection (added 2026-07-31 after entries #106 and #107 vanished) --------------
#
# WHY: both were written as "## #106 — Title" instead of "## 106. Title". ENTRY_RE missed them, they were
# dropped from the generated Index, and this script printed "unchanged … (105 entries indexed)" — a silent
# skip of exactly the kind Standard #4 forbids. An entry missing from the Index is invisible to the
# "have we seen this failure before?" grep that is the whole point of these files.
#
# The obvious check — "flag every ##/### that ENTRY_RE missed" — is WRONG here. Both files carry real
# section headers (`## Fixed Assumptions`, `## Bugs Caught by PR Review (Gemini PR#8)`,
# `### The gate was swallowing its own failures`, `## 2026-07-28 — PR #237 …`), so that check would have
# fired 10 times on a clean tree. A check that cries wolf on day one gets muted, which is worse than no
# check. So the test is INVERTED: a header is only suspect when it is ENTRY-SHAPED — it opens with an
# optional "#" and a digit, which no section title in either file does — and still fails ENTRY_RE.
_ENTRY_SHAPED_RE = re.compile(r"^#{2,3}\s+#?\d")
# …with one carve-out: gemini_review_patterns.md heads its narrative sections with an ISO date
# ("## 2026-07-28 — PR #237"). That is entry-shaped by accident of starting with a digit, so exclude a
# leading full date specifically — narrow and explicit, never a general "starts with a number" amnesty.
_DATED_SECTION_RE = re.compile(r"^#{2,3}\s+\d{4}-\d{2}-\d{2}\b")
_ANY_HEADER_RE = re.compile(r"^#{2,3}\s")


def find_malformed(lines):
    """Headers that were meant to be entries but will not parse. Returns [(lineno, text)]."""
    bad = []
    for i, ln in enumerate(lines, start=1):
        if not _ANY_HEADER_RE.match(ln):
            continue
        if ENTRY_RE.match(ln) or _DATED_SECTION_RE.match(ln):
            continue
        if _ENTRY_SHAPED_RE.match(ln):
            bad.append((i, ln.rstrip()))
    return bad


def find_numbering_faults(entries):
    """Duplicate or missing entry numbers. Entries are append-only and dense from 1, so a gap means an
    entry exists in the file but never reached the Index — the same silent loss, one step earlier."""
    faults = []
    nums = [n for n, _ in entries]
    seen = set()
    for n in nums:
        if n in seen:
            faults.append(f"#{n} appears more than once")
        seen.add(n)
    if nums:
        missing = sorted(set(range(1, max(nums) + 1)) - seen)
        if missing:
            faults.append("gap in the sequence: " + ", ".join(f"#{n}" for n in missing))
    return faults


def build_index(lines):
    entries = []
    for ln in lines:
        m = ENTRY_RE.match(ln)
        if m:
            entries.append((int(m.group(2)), m.group(3).strip()))
    entries.sort(key=lambda e: e[0])
    body = [START, "## Index", f"*{len(entries)} entries — grep `#N` or a keyword; full entry is the `#N.` header below.*", ""]
    body += [f"- **#{n}** — {lesson}" for n, lesson in entries]
    body += ["", END]
    return "\n".join(body), entries


def reindex(path, check_only=False):
    with open(path, encoding="utf-8") as f:
        text = f.read()
    lines = text.splitlines()
    index_block, entries = build_index(lines)
    n = len(entries)
    problems = [f"line {i}: {t}" for i, t in find_malformed(lines)] + find_numbering_faults(entries)

    if START in text and END in text:
        new = re.sub(re.escape(START) + r".*?" + re.escape(END), index_block, text, count=1, flags=re.DOTALL)
    else:
        # insert after the first H1 (`# …`) line + its trailing blank line
        out, inserted = [], False
        for i, ln in enumerate(lines):
            out.append(ln)
            if not inserted and ln.startswith("# "):
                out.append("")
                out.append(index_block)
                inserted = True
        if not inserted:                      # no H1 → prepend
            out = [index_block, ""] + lines
        new = "\n".join(out) + ("\n" if text.endswith("\n") else "")

    # A malformed entry is NOT a reason to skip the rewrite: the index should still reflect everything that
    # DID parse, so the run is idempotent and the fix is a one-line header edit + re-run. The failure is
    # reported by the exit code, not by refusing to write.
    stale = new != text
    if stale and not check_only:
        with open(path, "w", encoding="utf-8") as f:
            f.write(new)
    return n, stale, problems


def main():
    # --check is the CI/pre-push mode: report, never write. A gate that repairs the thing it is checking
    # would let a stale committed index pass by silently regenerating it, which is the "forgot to re-run"
    # hole CLAUDE.md B-2 currently leaves to discipline.
    check_only = "--check" in sys.argv[1:]
    total = 0
    problems = {}
    for path in FILES:
        try:
            n, stale, probs = reindex(path, check_only=check_only)
        except FileNotFoundError:
            # A missing case-law file is a REAL fault, not a shrug: these two paths are the whole system.
            # Previously this printed "skip" and returned 0, so a renamed/deleted file passed silently.
            print(f"❌ missing: {path}")
            problems[path] = ["file not found"]
            continue
        total += n
        if probs:
            problems.setdefault(path, []).extend(probs)
        if stale and check_only:
            problems.setdefault(path, []).append(
                "the Index is out of date — run `python3 tools/reindex_caselaw.py` and commit the result")
        if check_only:
            print(f"{'STALE' if stale else 'current'}: {path} ({n} entries indexed)")
        else:
            print(f"{'updated' if stale else 'unchanged'}: {path} ({n} entries indexed)")
    print(f"done — {total} entries across {len(FILES)} files.")

    if problems:
        print("\n❌ reindex_caselaw FAILED — entries that will never reach the Index:")
        for path, probs in problems.items():
            print(f"  {path}")
            for p in probs:
                print(f"    • {p}")
        print("\n  An entry header must read exactly `## N. Lesson` (or `### N. Lesson`).")
        print("  An entry missing from the Index is invisible to the grep these files exist for.")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
