#!/usr/bin/env python3
"""Regenerate the `## Index` block at the top of the two case-law files (Fable B-2).

assumptions_audit.md (97 entries) and gemini_review_patterns.md are read wholesale to recall "have we seen
this failure class?" — a 700+-line read for a one-line answer. This inserts/refreshes a scannable index of
`#N — <lesson>` (the entry HEADERS already ARE the one-sentence lessons), so recall is a 60-line read + a
grep. Re-runnable and idempotent (it replaces the block between the AUTO markers) — so it's ALSO the
maintenance mechanism: add an entry, re-run `python3 tools/reindex_caselaw.py`, commit. Stdlib-only.
"""
import re
import sys

FILES = (
    "docs/failures/assumptions_audit.md",
    "docs/failures/gemini_review_patterns.md",
)
ENTRY_RE = re.compile(r"^(#{2,3})\s+(\d+)\.\s+(.+?)\s*$")   # "## N. …" or "### N. …" (each file uses one level)
START = "<!-- INDEX:START (auto-generated by tools/reindex_caselaw.py — do not hand-edit) -->"
END = "<!-- INDEX:END -->"


def build_index(lines):
    entries = []
    for ln in lines:
        m = ENTRY_RE.match(ln)
        if m:
            entries.append((int(m.group(2)), m.group(3).strip()))
    entries.sort(key=lambda e: e[0])
    body = [START, "## Index", f"*{len(entries)} entries — grep `#N` or a keyword; full entry is the `#N.` header below.*", ""]
    body += [f"- **#{n}** — {lesson}" for n, lesson in entries]
    body += ["", END]
    return "\n".join(body), len(entries)


def reindex(path):
    with open(path, encoding="utf-8") as f:
        text = f.read()
    lines = text.splitlines()
    index_block, n = build_index(lines)

    if START in text and END in text:
        new = re.sub(re.escape(START) + r".*?" + re.escape(END), index_block, text, count=1, flags=re.DOTALL)
    else:
        # insert after the first H1 (`# …`) line + its trailing blank line
        out, inserted = [], False
        for i, ln in enumerate(lines):
            out.append(ln)
            if not inserted and ln.startswith("# "):
                out.append("")
                out.append(index_block)
                inserted = True
        if not inserted:                      # no H1 → prepend
            out = [index_block, ""] + lines
        new = "\n".join(out) + ("\n" if text.endswith("\n") else "")

    if new != text:
        with open(path, "w", encoding="utf-8") as f:
            f.write(new)
    return n, new != text


def main():
    total = 0
    for path in FILES:
        try:
            n, changed = reindex(path)
        except FileNotFoundError:
            print(f"skip (not found): {path}")
            continue
        total += n
        print(f"{'updated' if changed else 'unchanged'}: {path} ({n} entries indexed)")
    print(f"done — {total} entries across {len(FILES)} files.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
